//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using SharpDX.Mathematics.Interop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public abstract class BaseLine
    {
        public RawColor4 Color
        {
            get;
            set;
        }

        public float StartPointX
        {
            get;
            set;
        }

        public float EndPointX
        {
            get;
            set;
        }

        public float StartPointY
        {
            get;
            set;
        }

        public float EndPointY
        {
            get;
            set;
        }

        public float LineWidth
        {
            get;
            set;
        }
        public abstract void Calculate();
    }
}

