//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using SharpDX.Mathematics.Interop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public abstract class BaseLine
    {
        public virtual RawColor4 Color
        {
            get;
            set;
        }

        public virtual float StartPointX
        {
            get;
            set;
        }

        public virtual float EndPointX
        {
            get;
            set;
        }

        public virtual float StartPointY
        {
            get;
            set;
        }

        public virtual float EndPointY
        {
            get;
            set;
        }

        public virtual float LineWidth
        {
            get;
            set;
        }

        public virtual CanvasParam CanvasParam
        {
            get;
            set;
        }
        public String Caption { set; get; }
        public abstract void Draw();
    }
}

