//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public class CanvasParam
    {
        public SharpDX.Direct2D1.RenderTarget _renderTarget { set; get; }
        public SharpDX.DirectWrite.Factory dwFactory { set; get; }
        public SharpDX.Direct2D1.Factory factory { set; get; }
        /// <summary>
        /// 源点X
        /// </summary>
        public virtual float OriginX
        {
            get;
            set;
        }
        /// <summary>
        /// 源点Y
        /// </summary>
        public virtual float OriginY
        {
            get;
            set;
        }

        /// <summary>
        /// 水平长度
        /// </summary>
        public virtual float HorizontalLength
        {
            get;
            set;
        }

        /// <summary>
        /// 垂直长度
        /// </summary>
        public virtual float VerticalLength
        {
            get;
            set;
        }
        /// <summary>
        /// 距离边框距离
        /// </summary>
        public virtual float Padding
        {
            get;
            set;
        }

    }
}

