//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public class CoordinateAxis : BaseLine
    {
        public CoordinateAxis(CoordinateParam coordinateParam)
        {
            this.coordinateParam = coordinateParam;
        }
        CoordinateParam coordinateParam { set; get; }
        /// <summary>
        /// 坐标轴名字 用于识别
        /// </summary>
        public CoordinateAxisName Name { set; get; }
        /// <summary>
        /// 刻度最大值
        /// </summary>
        public float MaxValue { set; get; }
        /// <summary>
        /// 刻度最小值
        /// </summary>
        public float MinValue { set; get; }
        /// <summary>
        /// 刻度间隔
        /// </summary>
        public float Interval { get; set; }
        /// <summary>
        /// 单位刻度长度
        /// </summary>
        public float UnitLength { set; get; }
        /// <summary>
        /// 坐标方向分横向 或 纵向
        /// </summary>
        public LineDireciton lineDirection
        {
            get;
            set;
        }
        /// <summary>
        /// 坐标位置分 左 或 右
        /// </summary>
        public LineLocation lineLocation
        {
            get;
            set;
        }
        /// <summary>
        /// 是否显示坐标轴
        /// </summary>
        public LineVisible lineVisible
        {
            get;
            set;
        }
        /// <summary>
        /// 显示虚线
        /// </summary>
        public VirtualLineVisible virtualLineVisible
        {
            get;
            set;
        }
        /// <summary>
        /// 坐标轴的位置序号
        /// </summary>
        public int Index { set; get; }
        public override void Draw()
        {
            Calculate();
            throw new NotImplementedException();
        }
        /// <summary>
        /// 绘制刻度线
        /// </summary>
        private void DrawScale()
        {
            return;
        }
        /// <summary>
        /// 绘制标识
        /// </summary>
        private void DrawLegend()
        {
            throw new System.NotImplementedException();
        }
        private void Calculate()
        {
        }
        private void SetParam()
        { }
    }

}
