//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public class CoordinateParam
    {
        public string Caption { get; set; }
        public CoordinateAxisName Name { get; set; }
        public VirtualLineVisible virtualLineVisible { get; set; }
        public LineVisible lineVisible { get; set; }
        public LineDireciton lineDirection { get; set; }
        public LineLocation lineLocation { set; get; }
        public int MaxValue { get; set; }
        public int MinValue { get; set; }
        public float Interval { set; get; }
        public int Index { set; get; }
        public float UnitLength { set; get; }
        public float LineWidth { set; get; }
    }
}
