//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public class CoordinateParam
    {
        public virtual float ArrowBlankLength
        {
            get;
            set;
        }

        public virtual float ArrowLength
        {
            get;
            set;
        }

        /// <summary>
        /// 横轴长度
        /// </summary>
        public virtual float HLength
        {
            get;
            set;
        }

        /// <summary>
        /// 纵轴长度
        /// </summary>
        public virtual float VLength
        {
            get;
            set;
        }

    }
}
