//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CurveModelLib
{
    public enum LineDireciton
    {
        /// <summary>
        /// 水平方向
        /// </summary>
        Horizontal = 0,
        /// <summary>
        /// 垂直
        /// </summary>
        Vertical = 1,
    }
}